version: '3'

services:
  wazuh-agent:
    container_name: wazuh-agent
    image: samsonidowu/wazuh-agent-4.7.2:latest
    environment:
      - WAZUH_MANAGER_IP=192.168.186.129
      - WAZUH_MANAGER_PORT=1514
      - WAZUH_REGISTRATION_PASSWORD=admin
      - WAZUH_AGENT_NAME=docker-agent
    volumes:
      - ./ossec.conf:/var/ossec/etc/ossec.conf
      - /var/log/auth.log:/var/log/auth.log
      - /var/log/dpkg.log:/var/log/dpkg.log
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    ports:
      - "1514:1514"
    hostname: docker-agent